# Generated by Django 2.0 on 2018-12-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='template_file',
            field=models.FileField(upload_to='template_files'),
        ),
    ]
