# Generated by Django 2.0.6 on 2018-12-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentpost_image_attribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpost',
            name='image_attribution',
        ),
    ]
