# Generated by Django 2.0.6 on 2018-12-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_contentpost_image_attribution'),
        ('content', '0002_auto_20181229_1842'),
    ]

    operations = [
    ]
